### ISSUE TITLE
Mismatch in Dataset Statistics and class distribution 

### ISSUE THREAD

**Issue by vinodkkurmi** [roudimit/MUSIC_dataset#1]
@roudimit  Hi, There is a mismatch is the dataset statistics in json file and paper.
In the MUSIC_solo_videos.json file, there are total 577 videos ids present but the number mentioned in the paper is 565. The distribution of the classes is very different in the paper and in the JSON file. Could you please check this issue? 
Thanks

**Comment by roudimit** [comment]
Hi @vinodkkurmi, I will look into this soon and I will get back to you.

**Comment by roudimit** [comment]
Hi @vinodkkurmi, the distribution reported in the paper reflects the initial state of the dataset. We’ve updated the dataset since then to remove low quality videos and to add more good quality videos. We are working on enhancing the dataset and we are planning to release another version with more videos in the future. 

As you’ve mentioned, the distribution of videos is slightly different than in the paper. For reference, here is the new distribution: 

[(u'flute', 48),
 (u'acoustic_guitar', 89),
 (u'accordion', 60),
 (u'xylophone', 50),
 (u'erhu', 53),
 (u'tuba', 52),
 (u'saxophone', 25),
 (u'cello', 57),
 (u'violin', 53),
 (u'clarinet', 41),
 (u'trumpet', 43)]

**Comment by vinodkkurmi** [comment]
@roudimit  Thanks a lot.  
So it means, the results reported in the paper are not from the dataset distribution you mention above? 
If yes, then could you please tell us the results with the later dataset?
Thanks

**Comment by roudimit** [comment]
@vinodkkurmi I've now adjusted the distribution of the dataset to match the distribution that our results are reported on in the paper. There are total of 685 videos, with 536 solo videos and 149 duet videos.  The next release of the paper will have these updated numbers and an updated figure. Here is the distribution of the solo videos in the json file after my update, which will be shown in the paper once we release the next version: 

[(u'flute', 48),
 (u'acoustic_guitar', 56),
 (u'accordion', 60),
 (u'xylophone', 49),
 (u'erhu', 53),
 (u'tuba', 51),
 (u'saxophone', 25),
 (u'cello', 57),
 (u'violin', 53),
 (u'clarinet', 41),
 (u'trumpet', 43)]

**Comment by vinodkkurmi** [comment]
@roudimit  Thanks :)
